sudo: required
services:
  - docker
branches:
  # Restrict push builds to only master
  only:
  - master
before_install:
  # Fail immediately on any error
  - set -e
script:
  - echo $TRAVIS_PULL_REQUEST
  - docker-compose -f tests/docker-compose.yml -p scoringengine build
  - docker-compose -f tests/docker-compose.yml -p scoringengine up -d
  - docker run -it scoringengine_tester bash -c "/app/cc-test-reporter before-build"
  - docker run -it scoringengine_tester bash -c "flake8 --ignore E501 --exclude *__init__.py ./"
  - docker run -it scoringengine_tester bash -c "py.test --cov=scoring_engine --cov-report=xml:coverage.xml tests"
after_success:
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      docker run -it scoringengine_tester bash -c "/app/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
    fi
