sudo: required
services:
  - docker
branches:
  # Restrict push builds to only master
  only:
  - master
before_install:
  # Fail immediately on any error
  - set -e
install:
  # Build containers
  - docker-compose -f tests/docker-compose.yml -p scoringengine build
before_script:
  # Start up resources needed for tests
  - docker-compose -f tests/docker-compose.yml -p scoringengine up -d
  # Prep codeclimate reporting
  - docker run -it scoringengine_tester bash -c "/usr/bin/cc-test-reporter before-build"
script:
  # Check for pep8 compliance
  - docker run -it scoringengine_tester bash -c "flake8 --config .flake8 ./"
  # Run unit tests
  - docker run -it scoringengine_tester bash -c "py.test --cov=scoring_engine --cov-report=xml:coverage.xml tests"
after_success:
  # Push results to code climate
  - |
    if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
      docker run -it scoringengine_tester bash -c "/usr/bin/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
    fi
