language: python
python:
  - '3.5'
install:
  - pip install -e .
  - pip install -r tests/requirements.txt
services:
  - redis-server
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - py.test --cov=scoring_engine --cov-report=xml:coverage.xml tests
  - flake8 --ignore E501 --exclude *__init__.py ./
after_script:
  - >
      if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then \
        ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT ;\
      else \
        exit 0 ;\
      fi
