language: python
python:
  - '3.5'
install:
  - pip install -e .
  - pip install -r requirements.txt
services:
  - redis-server
script:
  - cp engine.conf.inc engine.conf
  - py.test --cov=scoring_engine tests
  - codeclimate-test-reporter
  - pycodestyle --show-source --ignore=E501,E402  ./
