---
version: '3'
services:
  redis:
    image: "redis:latest"
    healthcheck:
      test: ["CMD", "redis-cli", "-h", "127.0.0.1", "ping"]
      interval: 30s
      timeout: 3s
      retries: 10
    restart: on-failure
    volumes:
      - redis:/data
    networks:
      - default
    # ports:
    #   - 6379:6379
  mysql:
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_DATABASE=scoring_engine
      - MYSQL_USER=se_user
      - MYSQL_PASSWORD=CHANGEME
    restart: on-failure
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - default
    # ports:
    #   - 3306:3306
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - flask
    ports:
      - 80:80
      - 443:443
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost"]
      interval: 30s
      timeout: 3s
      retries: 10
    restart: on-failure
    networks:
      - default
  base:
    build:
      context: .
      dockerfile: ./docker/base/Dockerfile
    image: base:latest
  bootstrap:
    build:
      context: .
      dockerfile: ./docker/bootstrap/Dockerfile
    depends_on:
      - base
      - mysql
    healthcheck:
      test: ["CMD", "exit", "1"]
    restart: on-failure
    networks:
      - default
    environment:
      - SCORINGENGINE_EXAMPLE
      - SCORINGENGINE_OVERWRITE_DB
      - SCORINGENGINE_VERSION
  engine:
    build:
      context: .
      dockerfile: ./docker/engine/Dockerfile
    depends_on:
      - base
      - redis
      - bootstrap
    restart: on-failure
    networks:
      - default
    environment:
      - SCORINGENGINE_EXAMPLE
      - SCORINGENGINE_VERSION
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    depends_on:
      - base
      - redis
    restart: on-failure
    networks:
      - default
    environment:
      - SCORINGENGINE_EXAMPLE
      - SCORINGENGINE_VERSION
  flask:
    build:
      context: .
      dockerfile: ./docker/flask/Dockerfile
    depends_on:
      - base
      - mysql
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:5000"]
      interval: 30s
      timeout: 3s
      retries: 10
    restart: on-failure
    networks:
      - default
    environment:
      - SCORINGENGINE_VERSION

volumes:
  redis:
  mysql:

networks:
  default:
