---
version: '3'
services:
  testbed_icmp:
    build:
      context: .
      dockerfile: ./docker/testbed/icmp/Dockerfile
  testbed_web:
    build:
      context: .
      dockerfile: ./docker/testbed/web/Dockerfile
    # ports:
    #   - 80:80
    #   - 443:443
  testbed_ssh:
    build:
      context: .
      dockerfile: ./docker/testbed/ssh/Dockerfile
    # ports:
    #   - 22:22
  testbed_mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=CHANGEME
      - MYSQL_DATABASE=randomdb
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=CHANGEME
    # ports:
    #   - 3306:3306
