name: Tests
on:
  # Run on any pushes to all branches
  push:
    branches: "*"
  # Run every night
  schedule:
    - cron: "0 0 * * *"
  # Allow for manual run
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Tests
        run: make build-tests

      - name: Run tests
        run: make run-tests

      - name: Run integration tests
        run: ./tests/integration/run.sh

      - name: Test & publish code coverage
        uses: paambaati/codeclimate-action@v2.7.5
        env:
          CC_TEST_REPORTER_ID: ecb85ae3d9e46474810659154b2354f9340aa7c0f0662a209ef80311d208547a
        with:
          coverageCommand: npm run coverage
