name: Tests
on:
  # Run on any pushes to all branches
  push:
    branches: "*"
  # Run every night
  schedule:
    - cron: "0 0 * * *"
  # Allow for manual run
  workflow_dispatch:

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Tests
        run: make build-tests

      - name: Run tests
        run: make run-tests

      - name: Upload coverage data to coveralls.io
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run integration tests
        run: ./tests/integration/run.sh
